// ---------------- PORTFOLIO SHOWCASE DATA ----------------
export const baseData = [
  {
    id: "1",
    category: "Expected Energy Output",
    value: 520,
    step: 520,
    open: 0,
    valueLabel: "520 MWh",
    color: "#0042C4",
    lossPercent: "",
  },

  {
    id: "1-1",
    category: "Irradiance & Weather Loss",
    value: 30,
    step: 520,
    open: 490,
    valueLabel: "30 MWh",
    lossPercent: "-5.8%",
    color: "#8A2330",
    childData: [
      {
        id: "1-1-1",
        category: "Cloud Cover Impact",
        value: 18,
        step: 520,
        open: 502,
        valueLabel: "18 MWh",
        lossPercent: "-3.4%",
        color: "#CF4848",
      },
      {
        id: "1-1-2",
        category: "Temperature Loss",
        value: 12,
        step: 502,
        open: 490,
        valueLabel: "12 MWh",
        lossPercent: "-2.4%",
        color: "#CF4848",
      },
    ],
  },

  {
    id: "1-2",
    category: "Soiling Loss",
    value: 40,
    step: 490,
    open: 450,
    valueLabel: "40 MWh",
    lossPercent: "-7.7%",
    color: "#8A2330",
    childData: [
      {
        id: "1-2-1",
        category: "Dust Accumulation",
        value: 25,
        step: 490,
        open: 465,
        valueLabel: "25 MWh",
        lossPercent: "-4.8%",
        color: "#CF4848",
      },
      {
        id: "1-2-2",
        category: "Cleaning Delay",
        value: 15,
        step: 465,
        open: 450,
        valueLabel: "15 MWh",
        lossPercent: "-2.9%",
        color: "#CF4848",
      },
    ],
  },

  {
    id: "1-3",
    category: "System Losses",
    value: 35,
    step: 450,
    open: 415,
    valueLabel: "35 MWh",
    lossPercent: "-6.7%",
    color: "#8A2330",
    childData: [
      {
        id: "1-3-1",
        category: "Inverter Efficiency",
        value: 20,
        step: 450,
        open: 430,
        valueLabel: "20 MWh",
        lossPercent: "-3.8%",
        color: "#CF4848",
      },
      {
        id: "1-3-2",
        category: "DC Cable Loss",
        value: 15,
        step: 430,
        open: 415,
        valueLabel: "15 MWh",
        lossPercent: "-2.9%",
        color: "#CF4848",
      },
    ],
  },

  {
    id: "1-4",
    category: "Operational Losses",
    value: 45,
    step: 415,
    open: 370,
    valueLabel: "45 MWh",
    lossPercent: "-8.6%",
    color: "#8A2330",
    childData: [
      {
        id: "1-4-1",
        category: "Maintenance Downtime",
        value: 20,
        step: 415,
        open: 395,
        valueLabel: "20 MWh",
        lossPercent: "-3.8%",
        color: "#CF4848",
      },
      {
        id: "1-4-2",
        category: "Grid Outage",
        value: 25,
        step: 395,
        open: 370,
        valueLabel: "25 MWh",
        lossPercent: "-4.8%",
        color: "#CF4848",
      },
    ],
  },

  {
    id: "1-5",
    category: "Curtailment Loss",
    value: 20,
    step: 370,
    open: 350,
    valueLabel: "20 MWh",
    lossPercent: "-3.8%",
    color: "#8A2330",
    childData: [
      {
        id: "1-5-1",
        category: "Grid Restrictions",
        value: 12,
        step: 370,
        open: 358,
        valueLabel: "12 MWh",
        lossPercent: "-2.3%",
        color: "#CF4848",
      },
      {
        id: "1-5-2",
        category: "Export Limitations",
        value: 8,
        step: 358,
        open: 350,
        valueLabel: "8 MWh",
        lossPercent: "-1.5%",
        color: "#CF4848",
      },
    ],
  },

  {
    id: "2",
    category: "Actual Energy Generated",
    value: 350,
    step: 350,
    open: 0,
    valueLabel: "350 MWh",
    color: "#64D6FF",
    lossPercent: "",
  },
];